name: peters imac data
host: 192.168.20.12
user: peter
port: 22
ssh_key: ssh/id_ed25519
mode: data
filters:
- common-excludes.txt
- group-vms.txt
- group-dev.txt
- group-cloud.txt
- group-media.txt
- group-apps.txt
- group-hidden.txt
- macos-data.txt
includes: []
source_paths:
- /Users/peter
exclude:
- 'Movies/TV/'
- 'docker/'
- 'Music/Music/Music Library.musiclibrary/'
- 'Music/Music/Previous Libraries.localized/'
- 'Music/iTunes/'
- '*/Screen Shots/'
snapshot: true
delete_excluded: true
backup_root: /backup
