name: peters imac
host: 192.168.20.12
user: peter
port: 22
ssh_key: ssh/id_ed25519
mode: data
filters:
- common-excludes.txt
- macos-data.txt
includes: []
source_paths:
- /Users/peterdoyle
exclude: []
snapshot: false
delete_excluded: true
backup_root: /backup
